apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emule-tmp 
  namespace: vpn
  labels:
    app: vpn
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
