apiVersion: v1
kind: Service
metadata:
  name: socks5tcp 
  namespace: vpn 
  annotations:
    metallb.universe.tf/allow-shared-ip: vpn
  labels:
    app: vpn 
spec:
  ports:
  - name: port1
    port: 1080 
    targetPort: 1080
    protocol: TCP
  selector:
    app: vpn 
  externalTrafficPolicy: Cluster 
  type: LoadBalancer
  loadBalancerIP: 192.168.1.102
---
apiVersion: v1
kind: Service
metadata:
  name: socks5udp 
  namespace: vpn 
  annotations:
    metallb.universe.tf/allow-shared-ip: vpn
  labels:
    app: vpn 
spec:
  ports:
  - name: port2
    port: 1080 
    targetPort: 1080
    protocol: UDP
  selector:
    app: vpn 
  externalTrafficPolicy: Cluster 
  type: LoadBalancer
  loadBalancerIP: 192.168.1.102
---
apiVersion: v1
kind: Service
metadata:
  name: emuleweb
  namespace: vpn 
  annotations:
    metallb.universe.tf/allow-shared-ip: vpn
  labels:
    app: vpn 
spec:
  ports:
  - name: port3
    port: 4711 
    targetPort: 4711
    protocol: TCP
  selector:
    app: vpn 
  externalTrafficPolicy: Cluster 
  type: LoadBalancer
  loadBalancerIP: 192.168.1.102
---
apiVersion: v1
kind: Service
metadata:
  name: emulevnc
  namespace: vpn 
  annotations:
    metallb.universe.tf/allow-shared-ip: vpn
  labels:
    app: vpn 
spec:
  ports:
  - name: port4
    port: 8080 
    targetPort: 8080
    protocol: TCP
  selector:
    app: vpn 
  externalTrafficPolicy: Cluster 
  type: LoadBalancer
  loadBalancerIP: 192.168.1.102